import type { AnalysisType, ReportType } from "./types";

// ─── Markup tiers ───────────────────────────────────────────────────────────
export const MARKUP_TIERS: Array<{ maxCost: number; multiplier: number }> = [
  { maxCost: 2, multiplier: 1.6 },
  { maxCost: 6, multiplier: 1.5 },
  { maxCost: 15, multiplier: 1.4 },
  { maxCost: Infinity, multiplier: 1.35 },
];

// ─── Safety buffer ──────────────────────────────────────────────────────────
export const MIN_SAFETY_BUFFER_USD = 0.5;
export const SAFETY_BUFFER_PERCENT = 0.15;

// ─── Price floor ────────────────────────────────────────────────────────────
export const MIN_PRICE_USD = 1.5;

// ─── Invariant: price must be at least this multiple of internal cost ───────
export const MIN_PRICE_TO_COST_RATIO = 1.15;

// ─── AI analysis token costs ────────────────────────────────────────────────
// Haiku 4.5 Batch API pricing (as of 2025-05)
// Input: $0.80/MTok, Output: $0.40/MTok (batch)
// We estimate both input + output per item
export const AI_COST_PER_ANALYSIS: Record<
  AnalysisType,
  { inputTokensPerItem: number; outputTokensPerItem: number }
> = {
  sentiment: { inputTokensPerItem: 300, outputTokensPerItem: 100 },
  classification: { inputTokensPerItem: 250, outputTokensPerItem: 50 },
  pain_points: { inputTokensPerItem: 400, outputTokensPerItem: 150 },
  summary: { inputTokensPerItem: 500, outputTokensPerItem: 200 },
};

// Haiku 4.5 Batch pricing per million tokens
export const HAIKU_BATCH_INPUT_PER_MTOK = 0.8;
export const HAIKU_BATCH_OUTPUT_PER_MTOK = 0.4;

// ─── Report generation costs ────────────────────────────────────────────────
// Generated by Sonnet 4.6: Input ~$3/MTok, Output ~$15/MTok
// executive: concise summary (~2k output), professional: balanced (~4k), technical: deep-dive (~8k)
export const REPORT_COSTS: Record<
  ReportType,
  { inputTokens: number; outputTokens: number }
> = {
  none: { inputTokens: 0, outputTokens: 0 },
  executive: { inputTokens: 6000, outputTokens: 2000 },
  professional: { inputTokens: 10000, outputTokens: 4000 },
  technical: { inputTokens: 15000, outputTokens: 8000 },
};

export const SONNET_INPUT_PER_MTOK = 3.0;
export const SONNET_OUTPUT_PER_MTOK = 15.0;

// ─── Chatbot flat fee (Strategy B) ──────────────────────────────────────────
export const CHATBOT_FLAT_FEE_USD = 0.05;

// ─── Cost cap ───────────────────────────────────────────────────────────────
export const COST_CAP_THRESHOLD = 0.85;
